### ISSUE TITLE
CONTRIB GUIDELINES?

### ISSUE THREAD

**Issue by cdecompilador** [Abde5/GBT-Emulator#1]
Por saber que estilo usar a la hora de programar en c, y tamaño máximo/temas máximos por commit.
Yo propongo esto para el estilo:
```c
/// Header: foo.h

/* Description of what foo does */
void foo(int a);

/// Source: foo.c

void foo(int a) {
   // Operate over `a` adding 1
   a += 1;
  
   // Substract 2 to `a`
   a -= 2;

   return a;
}
```
La idea es que la descripción de lo que hacen las funciones esté en el header y luego en su implementación(esté en el propio header o en otro archivo) indicar con comentarios cada bloque de instrucciones que se esta haciendo, en el ejemplo de arriba es algo redundante, pero el ejemplo de la función `read_file` de mi [fork](https://github.com/cdecompilador/GBT-Emulator/blob/main/src/tools.c) puede verse con más sentido esta manera de comentar, no teniendo que ser muy extenso, únicamente que de un vistazo rápido un nuevo contribuidor sepa que está pasando en el código y que sea "beginner friendly" para los espectadores que están empezando en la programación colaborativa viéndote en twitch.

**Comment by Abde5** [comment]
¡Buenas!

Muchísimas gracias por el interés y por querer contribuir al proyecto. Por desgracia, no creo que se pueda tener guidelines estrictas por ahora por varias razones:

- Programar en vivo nunca será limpio, y no creo que pueda llegar a hacerlo.
- No tengo mucho tiempo libre aparte de los streams.
- Me gustaría guardar la filosofía de "todo lo que veis en stream es lo que está en el emulador". Si hace falta, hacer sesiones de limpieza en stream.

Sin embargo, no me importa que añadas comentarios, pero no debuguees ninguna funcionalidad (como por ejemplo en tu pull request -> segfault, es porque aun no hemos visto en stream como resolver ese tipo de errores) porque justamente el objetivo es enseñar en vivo todo el proceso del desarrollo de un emulador. Te haré review de #2 porque me gusta que hagas un Makefile compatible con todos los OS.
